INSERT INTO Country VALUES
('','Afghanistan'),
('','Albania'),
('','Algeria'),
('','Andorra'),
('','Angola'),
('','Antigua & Deps'),
('','Argentina'),
('','Armenia'),
('','Australia'),
('','Austria'),
('','Azerbaijan'),
('','Bahamas'),
('','Bahrain'),
('','Bangladesh'),
('','Barbados'),
('','Belarus'),
('','Belgium'),
('','Belize'),
('','Benin'),
('','Bhutan'),
('','Bolivia'),
('','Bosnia Herzegovina'),
('','Botswana'),
('','Brazil'),
('','Brunei'),
('','Bulgaria'),
('','Burkina'),
('','Burundi'),
('','Cambodia'),
('','Cameroon'),
('','Canada'),
('','Cape Verde'),
('','Central African Rep'),
('','Chad'),
('','Chile'),
('','China'),
('','Colombia'),
('','Comoros'),
('','Congo'),
('','Congo {Democratic Rep}'),
('','Costa Rica'),
('','Croatia'),
('','Cuba'),
('','Cyprus'),
('','Czech Republic'),
('','Denmark'),
('','Djibouti'),
('','Dominica'),
('','Dominican Republic'),
('','East Timor'),
('','Ecuador'),
('','Egypt'),
('','El Salvador'),
('','Equatorial Guinea'),
('','Eritrea'),
('','Estonia'),
('','Ethiopia'),
('','Fiji'),
('','Finland'),
('','France'),
('','Gabon'),
('','Gambia'),
('','Georgia'),
('','Germany'),
('','Ghana'),
('','Greece'),
('','Grenada'),
('','Guatemala'),
('','Guinea'),
('','Guinea-Bissau'),
('','Guyana'),
('','Haiti'),
('','Honduras'),
('','Hungary'),
('','Iceland'),
('','India'),
('','Indonesia'),
('','Iran'),
('','Iraq'),
('','Ireland {Republic}'),
('','Israel'),
('','Italy'),
('','Ivory Coast'),
('','Jamaica'),
('','Japan'),
('','Jordan'),
('','Kazakhstan'),
('','Kenya'),
('','Kiribati'),
('','Korea North'),
('','Korea South'),
('','Kosovo'),
('','Kuwait'),
('','Kyrgyzstan'),
('','Laos'),
('','Latvia'),
('','Lebanon'),
('','Lesotho'),
('','Liberia'),
('','Libya'),
('','Liechtenstein'),
('','Lithuania'),
('','Luxembourg'),
('','Macedonia'),
('','Madagascar'),
('','Malawi'),
('','Malaysia'),
('','Maldives'),
('','Mali'),
('','Malta'),
('','Marshall Islands'),
('','Mauritania'),
('','Mauritius'),
('','Mexico'),
('','Micronesia'),
('','Moldova'),
('','Monaco'),
('','Mongolia'),
('','Montenegro'),
('','Morocco'),
('','Mozambique'),
('','Myanmar, {Burma}'),
('','Namibia'),
('','Nauru'),
('','Nepal'),
('','Netherlands'),
('','New Zealand'),
('','Nicaragua'),
('','Niger'),
('','Nigeria'),
('','Norway'),
('','Oman'),
('','Pakistan'),
('','Palau'),
('','Panama'),
('','Papua New Guinea'),
('','Paraguay'),
('','Peru'),
('','Philippines'),
('','Poland'),
('','Portugal'),
('','Qatar'),
('','Romania'),
('','Russian Federation'),
('','Rwanda'),
('','St Kitts & Nevis'),
('','St Lucia'),
('','Saint Vincent & the Grenadines'),
('','Samoa'),
('','San Marino'),
('','Sao Tome & Principe'),
('','Saudi Arabia'),
('','Senegal'),
('','Serbia'),
('','Seychelles'),
('','Sierra Leone'),
('','Singapore'),
('','Slovakia'),
('','Slovenia'),
('','Solomon Islands'),
('','Somalia'),
('','South Africa'),
('','South Sudan'),
('','Spain'),
('','Sri Lanka'),
('','Sudan'),
('','Suriname'),
('','Swaziland'),
('','Sweden'),
('','Switzerland'),
('','Syria'),
('','Taiwan'),
('','Tajikistan'),
('','Tanzania'),
('','Thailand'),
('','Togo'),
('','Tonga'),
('','Trinidad & Tobago'),
('','Tunisia'),
('','Turkey'),
('','Turkmenistan'),
('','Tuvalu'),
('','Uganda'),
('','Ukraine'),
('','United Arab Emirates'),
('','United Kingdom'),
('','United States'),
('','Uruguay'),
('','Uzbekistan'),
('','Vanuatu'),
('','Vatican City'),
('','Venezuela'),
('','Vietnam'),
('','Yemen'),
('','Zambia'),
('','Zimbabwe');
INSERT INTO City VALUES
 ('','Belfast', '186'),
 ('','Birmingham', '186'),
 ('','Manchester', '186'),
 ('','Doncaster', '186'),
 ('','Cardiff', '186'),
 ('','Bristol', '186'),
 ('','Liverpool', '186'),
 ('','London', '186'),
 ('','Bournemouth', '186'),
 ('','Southampton', '186'),
 ('','Leeds', '186'),
 ('','Newcastle', '186'),
 ('','Nottingham', '186'),
 ('','Aberdeen', '186'),
 ('','Glasgow', '186'),
 ('','Edinburgh', '186'),
 ('','Norwich', '186'),
 ('','Exeter', '186'),
 ('','Bath', '186'),
 ('','Bradford', '186'),
 ('','Brighton & Hove', '186'),
 ('','Cambridge', '186'),
 ('','Canterbury', '186'),
 ('','Carlisle', '186'),
 ('','Chelmsford', '186'),
 ('','Chester', '186'),
 ('','Chichester', '186'),
 ('','City of London', '186'),
 ('','City of Westminster', '186'),
 ('','Coventry', '186'),
 ('','Derby', '186'),
 ('','Durham', '186'),
 ('','Ely', '186'),
 ('','Gloucester', '186'),
 ('','Hereford', '186'),
 ('','Kingston-upon-Hull', '186'),
 ('','Lancaster', '186'),
 ('','Leicester', '186'),
 ('','Lichfield', '186'),
 ('','Lincoln', '186'),
 ('','Newcastle-upon-Tyne', '186'),
 ('','Oxford', '186'),
 ('','Peterborough', '186'),
 ('','Plymouth', '186'),
 ('','Portsmouth', '186'),
 ('','Preston', '186'),
 ('','Ripon', '186'),
 ('','Salford', '186'),
 ('','Salisbury', '186'),
 ('','Sheffield', '186'),
 ('','St Albans', '186'),
 ('','Stoke-on-Trent', '186'),
 ('','Sunderland', '186'),
 ('','Truro', '186'),
 ('','Wakefield', '186'),
 ('','Wells', '186'),
 ('','Winchester', '186'),
 ('','Wolverhampton', '186'),
 ('','Worcester', '186'),
 ('','York', '186');
INSERT INTO postcode VALUES
('','﻿BT29 4AB', '1'),
('','BT3 9JH', '1'),
('','B26 3QJ', '2'),
('','M90 1QX', '3'),
('','DN9 3RH', '4'),
('','CF62 3BD', '5'),
('','BS48 3DY', '6'),
('','L24 1YD', '7'),
('','LU2 9LY', '8'),
('','BH23 6SE', '9'),
('','SO18 2NL', '10'),
('','RH6 0NP', '8'),
('','TW6', '8'),
('','LS19 7TU', '11'),
('','NE13 8BZ', '12'),
('','DE74 2SA', '13'),
('','AB21 7DU', '14'),
('','PA3 2SW', '15'),
('','EH12 9DN', '16'),
('','NR6 6JA', '17'),
('','CM24 1QW', '8'),
('','EX5 2BD', '18');
